export const Api = {
  authSessionDetail: "/auth/session-detail",
  reports: "/reports",
  reportStatus: (id: string) => `/reports/${id}/status`,
  reportResolve: (id: string) => `/reports/${id}/resolve`,
  myReports: "/reports/me",
  reportsDashboard: "/reports/dashboard",
  reportLocations: "/reports/locations",
  agencyLocations: "/agencies/locations",

  notifications: "/notifications",
  notificationUnreadCount: "/notifications/unread-count",
  notificationRead: (id: string) => `/notifications/${id}/read`,
  notificationReadAll: "/notifications/read-all",

  adminOverview: "/admin/overview",
  adminDinas: "/admin/dinas",
  adminDinasById: (id: string) => `/admin/dinas/${id}`,
  adminCabang: "/admin/cabang",
  adminCabangById: (id: string) => `/admin/cabang/${id}`,
  adminKategori: "/admin/kategori",
  adminKategoriById: (id: string) => `/admin/kategori/${id}`,
  adminUsers: "/admin/users",
  adminUserById: (id: string) => `/admin/users/${id}`,
  adminUserResetPassword: (id: string) => `/admin/users/${id}/reset-password`,
  adminUserAssignPetugas: (id: string) => `/admin/users/${id}/assign-petugas`,
} as const;
