export const Api = {
  authSessionDetail: "/auth/session-detail",
  reports: "/reports",
  reportStatus: (id: string) => `/reports/${id}/status`,
  reportClarification: (id: string) => `/reports/${id}/clarification`,
  reportVote: (id: string) => `/reports/${id}/vote`,
  reportRating: (id: string) => `/reports/${id}/rating`,
  reportResolve: (id: string) => `/reports/${id}/resolve`,
  reportClaim: (id: string) => `/reports/${id}/claim`,
  myReports: "/reports/me",
  reportsDashboard: "/reports/dashboard",
  reportLocations: "/reports/locations",
  agencyLocations: "/agencies/locations",

  notifications: "/notifications",
  notificationUnreadCount: "/notifications/unread-count",
  notificationRead: (id: string) => `/notifications/${id}/read`,
  notificationReadAll: "/notifications/read-all",

  adminOverview: "/admin/overview",
  adminDinas: "/admin/dinas",
  adminDinasActivity: "/admin/dinas/activity",
  adminDinasById: (id: string) => `/admin/dinas/${id}`,
  adminCabang: "/admin/cabang",
  adminCabangActivity: "/admin/cabang/activity",
  adminCabangById: (id: string) => `/admin/cabang/${id}`,
  adminKategori: "/admin/kategori",
  adminKategoriActivity: "/admin/kategori/activity",
  adminKategoriById: (id: string) => `/admin/kategori/${id}`,
  adminUsers: "/admin/users",
  adminUserActivity: "/admin/users/activity",
  adminUserById: (id: string) => `/admin/users/${id}`,
  adminUserResetPassword: (id: string) => `/admin/users/${id}/reset-password`,
  adminUserAssignPetugas: (id: string) => `/admin/users/${id}/assign-petugas`,

  adminLaporan: "/admin/laporan",
  adminReportActivity: "/admin/laporan/activity",
  adminLaporanById: (id: string) => `/admin/laporan/${id}`,
  adminLaporanStatus: (id: string) => `/admin/laporan/${id}/status`,
  adminLaporanAssign: (id: string) => `/admin/laporan/${id}/assign`,
} as const;
