export const QUERY_KEYS = {
  AUTH_SESSION_DETAIL: "auth-session-detail",
  MY_REPORTS: "my-reports",
  REPORTS_DASHBOARD: "reports-dashboard",
  REPORTS_LOCATIONS: "reports-locations",
  AGENCIES_LOCATIONS: "agencies-locations",
  NOTIFICATIONS: "notifications",
  NOTIFICATIONS_UNREAD_COUNT: "notifications-unread-count",

  ADMIN_OVERVIEW: "admin_overview",
  ADMIN_DINAS: "admin_dinas",
  ADMIN_DINAS_ACTIVITY: "admin_dinas_activity",
  ADMIN_CABANG: "admin_cabang",
  ADMIN_CABANG_ALL: "admin_cabang_all",
  ADMIN_CABANG_ACTIVITY: "admin_cabang_activity",
  ADMIN_KATEGORI: "admin_kategori",
  ADMIN_KATEGORI_ACTIVITY: "admin_kategori_activity",
  ADMIN_USERS: "admin_users",
  ADMIN_USER_ACTIVITY: "admin_user_activity",
  ADMIN_LAPORAN: "admin_laporan",
  ADMIN_REPORT_ACTIVITY: "admin_report_activity",
} as const;
